### PR TITLE
Add manpage

### PR DESCRIPTION
**Pull request by eggbean**
I made a manpage for git-identity to make it easier for me to remember how to use it. I made it using [ronn](https://github.com/rtomayko/ronn).

```
$ cp README.md git-identity.1.ronn
$ ronn git-identity.1.ronn
$ gzip git-identity.1
$ sudo mv git-identity.1.gz /usr/share/man/man1/
$ sudo mandb
```

It was lightly edited so that it works with `whatis`, but probably needs further work to make it more like a proper manpage. I think this is better than no manpage at all though.

I _think_ the location within the 'man' directory is correct for working with `basher`.

### CODE REVIEW

**Comment by somini** [comment]
I think you want to include the source code on the repository, and not just the final manpage.

**Comment by eggbean** [comment]
I have added the file for generating the man page as shown above. It's actually just the `README.md` copied and renamed with three lines added.

**Comment by madx** [comment]
I'm *__a bit__* late but I merged it since it only adds new files. I haven't checked if it's still in sync with the `README.md` yet.

**Comment by eggbean** [comment]
@madx It doesn't look like the README.md has changed since I made it, so it should be fine. Cheers.

**Pull request merged**
